2019-02-16 22:05:58,655 INFO     main.py         INITIALIZING LITTER BUG... 
2019-02-16 22:05:58,885 INFO     LitterBug.py    Generating clip...
2019-02-16 22:05:59,101 INFO     Downloaders.py  Downloading videos...
2019-02-16 22:05:59,102 INFO     googleapiclient.discovery URL being requested: GET https://www.googleapis.com/discovery/v1/apis/youtube/v3/rest?key=AIzaSyBSJypxzItzh2LddmeV4EsNq0GXuEXAp1M
2019-02-16 22:05:59,557 INFO     utils.py        Generating keyword...
2019-02-16 22:06:00,976 INFO     googleapiclient.discovery URL being requested: GET https://www.googleapis.com/youtube/v3/search?q=windup&part=id%2C+snippet&type=video&key=AIzaSyBSJypxzItzh2LddmeV4EsNq0GXuEXAp1M&alt=json
2019-02-16 22:06:01,639 INFO     utils.py        Generating keyword...
2019-02-16 22:06:02,400 INFO     googleapiclient.discovery URL being requested: GET https://www.googleapis.com/youtube/v3/search?q=compel&part=id%2C+snippet&type=video&key=AIzaSyBSJypxzItzh2LddmeV4EsNq0GXuEXAp1M&alt=json
2019-02-16 22:06:02,868 INFO     utils.py        Generating keyword...
2019-02-16 22:06:05,578 INFO     googleapiclient.discovery URL being requested: GET https://www.googleapis.com/youtube/v3/search?q=Alberto&part=id%2C+snippet&type=video&key=AIzaSyBSJypxzItzh2LddmeV4EsNq0GXuEXAp1M&alt=json
2019-02-16 22:06:10,240 WARNING  main.py         Exception occured at main.py
2019-02-16 22:06:10,240 ERROR    main.py         [Errno 2] No such file or directory: '/Users/nicholaskelton/Project-Litter-Bug/media/video/.temp'
2019-02-16 22:06:10,240 INFO     LitterBug.py    Handling exception...
2019-02-16 22:06:15,674 INFO     LitterBug.py    Cleaning up...
2019-02-16 22:06:15,868 INFO     utils.py        Clearing folder: /Users/nicholaskelton/Project-Litter-Bug/media/video/
2019-02-16 22:07:33,884 INFO     main.py         INITIALIZING LITTER BUG... 
2019-02-16 22:07:34,018 INFO     LitterBug.py    Generating clip...
2019-02-16 22:07:34,191 INFO     Downloaders.py  Downloading videos...
2019-02-16 22:07:34,192 INFO     googleapiclient.discovery URL being requested: GET https://www.googleapis.com/discovery/v1/apis/youtube/v3/rest?key=AIzaSyBSJypxzItzh2LddmeV4EsNq0GXuEXAp1M
2019-02-16 22:07:34,470 INFO     utils.py        Generating keyword...
2019-02-16 22:07:35,513 INFO     googleapiclient.discovery URL being requested: GET https://www.googleapis.com/youtube/v3/search?q=leftover&part=id%2C+snippet&type=video&key=AIzaSyBSJypxzItzh2LddmeV4EsNq0GXuEXAp1M&alt=json
2019-02-16 22:07:36,034 INFO     utils.py        Generating keyword...
2019-02-16 22:07:36,851 INFO     googleapiclient.discovery URL being requested: GET https://www.googleapis.com/youtube/v3/search?q=pancake&part=id%2C+snippet&type=video&key=AIzaSyBSJypxzItzh2LddmeV4EsNq0GXuEXAp1M&alt=json
2019-02-16 22:07:37,282 INFO     utils.py        Generating keyword...
2019-02-16 22:07:38,093 INFO     googleapiclient.discovery URL being requested: GET https://www.googleapis.com/youtube/v3/search?q=bone&part=id%2C+snippet&type=video&key=AIzaSyBSJypxzItzh2LddmeV4EsNq0GXuEXAp1M&alt=json
2019-02-16 22:07:41,688 WARNING  main.py         Exception occured at main.py
2019-02-16 22:07:41,688 ERROR    main.py         [Errno 2] No such file or directory: '/Users/nicholaskelton/Project-Litter-Bug/media/video/.temp'
2019-02-16 22:07:41,688 INFO     LitterBug.py    Handling exception...
2019-02-16 22:07:47,031 INFO     LitterBug.py    Cleaning up...
2019-02-16 22:56:08,764 INFO     main.py         INITIALIZING LITTER BUG... 
2019-02-16 22:56:08,928 INFO     LitterBug.py    Generating clip...
2019-02-16 22:56:09,156 INFO     LitterBug.py    Downloading content...
2019-02-16 22:56:09,157 INFO     Downloaders.py  Downloading videos...
2019-02-16 22:56:09,158 INFO     googleapiclient.discovery URL being requested: GET https://www.googleapis.com/discovery/v1/apis/youtube/v3/rest?key=AIzaSyBSJypxzItzh2LddmeV4EsNq0GXuEXAp1M
2019-02-16 22:56:09,610 INFO     utils.py        Generating keyword...
2019-02-16 22:56:10,752 INFO     googleapiclient.discovery URL being requested: GET https://www.googleapis.com/youtube/v3/search?q=hardbound&part=id%2C+snippet&type=video&key=AIzaSyBSJypxzItzh2LddmeV4EsNq0GXuEXAp1M&alt=json
2019-02-16 22:56:11,392 INFO     utils.py        Generating keyword...
2019-02-16 22:56:12,450 INFO     googleapiclient.discovery URL being requested: GET https://www.googleapis.com/youtube/v3/search?q=compass&part=id%2C+snippet&type=video&key=AIzaSyBSJypxzItzh2LddmeV4EsNq0GXuEXAp1M&alt=json
2019-02-16 22:56:13,441 INFO     utils.py        Generating keyword...
2019-02-16 22:56:14,474 INFO     googleapiclient.discovery URL being requested: GET https://www.googleapis.com/youtube/v3/search?q=claret&part=id%2C+snippet&type=video&key=AIzaSyBSJypxzItzh2LddmeV4EsNq0GXuEXAp1M&alt=json
2019-02-16 22:56:18,544 WARNING  main.py         Exception occured at main.py
2019-02-16 22:56:18,544 ERROR    main.py         [Errno 2] No such file or directory: '/Users/nicholaskelton/Project-Litter-Bug/media/video/.temp'
2019-02-16 22:56:18,544 INFO     LitterBug.py    Handling exception...
2019-02-16 22:56:23,871 INFO     LitterBug.py    Cleaning up...
2019-02-16 22:56:23,977 INFO     utils.py        Clearing folder: /Users/nicholaskelton/Project-Litter-Bug/media/video/
